/**
 * Release-It Configuration Template
 *
 * Generates a release-it configuration file (.release-it.cjs) that integrates
 * with PipeCraft's versioning system and conventional commits workflow.
 *
 * This template creates a release-it configuration that:
 * - Uses conventional commits for version bumping
 * - Integrates with GitHub releases
 * - Supports custom version bump rules
 * - Works with PipeCraft's trunk-based development flow
 *
 * @module templates/release-it.cjs.tpl
 */

import { type PinionContext, renderTemplate, toFile } from '@featherscloud/pinion'
import { logger } from '../utils/logger.js'
import { buildReleaseItConfig } from '../utils/release-it-config.js'

/**
 * Generate release-it configuration content
 *
 * Creates a release-it configuration that integrates with PipeCraft's
 * versioning system and supports the configured semver bump rules.
 *
 * @param {any} ctx - Context containing semver configuration
 * @param {any} ctx.semver - Semantic versioning configuration
 * @param {any} ctx.semver.bumpRules - Version bump rules mapping
 * @returns {string} JavaScript configuration content
 */
const releaseItTemplate = (ctx: any) =>
  // `generate` and `init --with-versioning` both write .release-it.cjs. One builder, so
  // they cannot drift apart again — see src/utils/release-it-config.ts and #496.
  buildReleaseItConfig(ctx.config ?? ctx)

/**
 * Release-It configuration generator
 *
 * Generates a release-it configuration file that integrates with PipeCraft's
 * versioning system and conventional commits workflow.
 *
 * @param {PinionContext} ctx - Pinion generator context
 * @returns {Promise<PinionContext>} Updated context after file generation
 *
 * @example
 * ```typescript
 * // Called by PipeCraft when generating workflows
 * await generate({
 *   cwd: '/path/to/project',
 *   semver: {
 *     bumpRules: {
 *       feat: 'minor',
 *       fix: 'patch',
 *       breaking: 'major'
 *     }
 *   }
 * })
 * ```
 */
export const generate = (ctx: PinionContext) =>
  Promise.resolve(ctx)
    .then(ctx => {
      logger.verbose('📝 Generating release-it configuration...')
      return ctx
    })
    .then(
      renderTemplate(
        (ctx: any) => releaseItTemplate(ctx),
        toFile('.release-it.cjs'),
        // Entirely generated by buildReleaseItConfig() — no user-editable region to
        // preserve. Without force, Pinion skips the file once it exists, so a later
        // semver.bumpRules change never reaches .release-it.cjs: the file keeps the
        // stale rule and `generate` still exits 0. See enforce-pr-target.yml.tpl.ts for
        // the same reasoning.
        { force: true }
      )
    )
    .then(ctx => {
      logger.verbose('✅ Generated .release-it.cjs')
      return ctx
    })
