{
  name: "Pipeline",

  run-name: "${{ github.event_name == 'pull_request' && !contains('develop,main', github.head_ref) && github.event.pull_request.title || github.ref_name }} #${{ inputs.run_number || github.run_number }}${{ inputs.version && format(' - {0}', inputs.version) || '' }}",

  on: { workflow_dispatch: { inputs: { version: { description: The version to deploy, required: false, type: string }, baseRef: { description: The base reference for comparison, required: false, type: string }, run_number: { description: The original run number from develop branch, required: false, type: string }, commitSha: { description: The exact commit SHA to checkout and test, required: false, type: string } } }, workflow_call: { inputs: { version: { description: The version to deploy, required: false, type: string }, baseRef: { description: The base reference for comparison, required: false, type: string }, run_number: { description: The original run number from develop branch, required: false, type: string }, commitSha: { description: The exact commit SHA to checkout and test, required: false, type: string } } }, push: { branches: [ develop, main ] }, pull_request: { types: [ opened, synchronize, reopened ], branches: [ develop ] } },
  jobs:
    {
      #=============================================================================
    #CHANGES DETECTION (⚠️  Managed by Pipecraft - do not modify)
    #=============================================================================
    #Detects which domains have changed using path-based detection

      changes:

        #=============================================================================
        #CHANGES DETECTION (⚠️  Managed by Pipecraft - do not modify)
        #=============================================================================
        #Detects which domains have changed using path-based detection

        { runs-on: ubuntu-latest, steps: [ { uses: actions/checkout@v4, with: { ref: "${{ inputs.commitSha || github.sha }}", fetch-depth: 0 } }, { uses: ./.github/actions/detect-changes, id: detect, with: { baseRef: "${{ inputs.baseRef || 'main' }}" } } ], outputs: { app: "${{ steps.detect.outputs.app }}" } },
      #=============================================================================
    #TESTING JOBS (✅ Customize these with your test logic)
    #=============================================================================
    #These jobs run tests for each domain when changes are detected.
    #Replace the TODO comments with your actual test commands.

      test-app:

        #=============================================================================
        #TESTING JOBS (✅ Customize these with your test logic)
        #=============================================================================
        #These jobs run tests for each domain when changes are detected.
        #Replace the TODO comments with your actual test commands.

        {
          needs: changes,
          if: "${{ needs.changes.outputs.app == 'true' }}",
          runs-on: ubuntu-latest,
          steps:
            [
              { uses: actions/checkout@v4, with: { ref: "${{ inputs.commitSha || github.sha }}" } },
              # TODO: Replace with your app test logic
              {
                  name: Run app tests,
                  run: 'echo "Running tests for app domain"

                    echo "Replace this with your actual test commands"

                    # Example: npm test -- --testPathPattern=app

                    '
                }
            ]
        },
      #=============================================================================
    #VERSIONING (⚠️  Managed by Pipecraft - do not modify)
    #=============================================================================
    #Calculates the next semantic version based on conventional commits.
    #Only runs on push events (skipped on pull requests).

      version:

        #=============================================================================
        #VERSIONING (⚠️  Managed by Pipecraft - do not modify)
        #=============================================================================
        #Calculates the next semantic version based on conventional commits.
        #Only runs on push events (skipped on pull requests).

        { if: "${{ always() && github.event_name != 'pull_request' && (needs.test-app.result == 'success') && needs.test-app.result != 'failure' }}", needs: [ changes, test-app ], runs-on: ubuntu-latest, steps: [ { uses: actions/checkout@v4, with: { ref: "${{ inputs.commitSha || github.sha }}" } }, { uses: ./.github/actions/calculate-version, id: version, with: { baseRef: "${{ inputs.baseRef || 'main' }}", commitSha: "${{ inputs.commitSha || github.sha }}" } } ], outputs: { version: "${{ steps.version.outputs.version }}" } },
      #=============================================================================
    #DEPLOYMENT JOBS (✅ Customize these with your deploy logic)
    #=============================================================================
    #These jobs deploy each domain when changes are detected and tests pass.
    #Replace the TODO comments with your actual deployment commands.

      deploy-app:

        #=============================================================================
        #DEPLOYMENT JOBS (✅ Customize these with your deploy logic)
        #=============================================================================
        #These jobs deploy each domain when changes are detected and tests pass.
        #Replace the TODO comments with your actual deployment commands.

        {
          needs: [ version, changes ],
          if: "${{ always() && needs.version.result == 'success' && needs.changes.outputs.app == 'true' }}",
          runs-on: ubuntu-latest,
          steps:
            [
              { uses: actions/checkout@v4, with: { ref: "${{ inputs.commitSha || github.sha }}" } },
              # TODO: Replace with your app deployment logic
              {
                  name: Deploy app,
                  run: 'echo "Deploying app with version ${{ needs.version.outputs.version }}"

                    echo "Replace this with your actual deploy commands"

                    # Example: npm run deploy:app

                    '
                }
            ]
        },
      #=============================================================================
    #TAG & PROMOTE (⚠️  Managed by Pipecraft - do not modify)
    #=============================================================================
    #Creates git tags and promotes code through branch flow.

      tag:

        #=============================================================================
        #TAG & PROMOTE (⚠️  Managed by Pipecraft - do not modify)
        #=============================================================================
        #Creates git tags and promotes code through branch flow.

        { if: "${{ always() && github.event_name != 'pull_request' && github.ref_name == 'develop' && needs.version.result == 'success' && needs.version.outputs.version != '' && (needs.deploy-app.result != 'failure') && (needs.deploy-app.result == 'success') }}", needs: [ version, deploy-app ], runs-on: ubuntu-latest, steps: [ { uses: actions/checkout@v4, with: { ref: "${{ inputs.commitSha || github.sha }}" } }, { uses: ./.github/actions/create-tag, with: { version: "${{ needs.version.outputs.version }}", commitSha: "${{ inputs.commitSha || github.sha }}" } } ] },
      promote: { if: "${{ always() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && needs.version.result == 'success' && needs.version.outputs.version != '' && (needs.tag.result == 'success' || needs.tag.result == 'skipped') && (github.ref_name == 'develop') }}", needs: [ version, tag ], runs-on: ubuntu-latest, steps: [ { uses: actions/checkout@v4, with: { ref: "${{ inputs.commitSha || github.sha }}" } }, { uses: ./.github/actions/promote-branch, with: { version: "${{ needs.version.outputs.version }}", currentBranch: "${{ github.ref_name }}", nextBranch: "${{ 'main' }}", runNumber: "${{ github.run_number }}" } } ] },
      release: { if: "${{ always() && github.ref_name == 'main' && needs.version.result == 'success' && needs.version.outputs.version != '' && needs.tag.result == 'success' }}", needs: [ tag, version ], runs-on: ubuntu-latest, steps: [ { uses: actions/checkout@v4, with: { ref: "${{ inputs.commitSha || github.sha }}" } }, { uses: ./.github/actions/create-release, with: { version: "${{ needs.version.outputs.version }}", commitSha: "${{ inputs.commitSha || github.sha }}" } } ] }
    }
}
