name: 'Detect Changes'
description: 'Detect changes in different application domains based on file paths'
author: 'Pipecraft'

inputs:
  baseRef:
    description: 'Base reference to compare against'
    required: false
    default: 'main'

outputs:
  frontend:
    description: 'Whether frontend domain has changes'
    value: ${{ steps.merge.outputs.frontend }}
  backend:
    description: 'Whether backend domain has changes'
    value: ${{ steps.merge.outputs.backend }}
  api:
    description: 'Whether api domain has changes'
    value: ${{ steps.merge.outputs.api }}
  shared:
    description: 'Whether shared domain has changes'
    value: ${{ steps.merge.outputs.shared }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Base Branch
      id: set-base
      shell: bash
      run: |
        base_branch=${{ inputs.baseRef || 'main' }}
        echo "base_branch=$base_branch" >> $GITHUB_OUTPUT
        echo "base_branch=$base_branch" >> $GITHUB_ENV

    - name: Detect Changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.set-base.outputs.base_branch }}
        filters: |
          frontend:
            - 'src/frontend/**'
          backend:
            - 'src/backend/**'
          api:
            - 'src/api/**'
          shared:
            - 'src/shared/**'

    - name: Merge filter outputs
      id: merge
      shell: bash
      run: |
        echo "frontend=${{ contains(steps.filter.outputs.changes, 'frontend') }}" >> $GITHUB_OUTPUT
        echo "backend=${{ contains(steps.filter.outputs.changes, 'backend') }}" >> $GITHUB_OUTPUT
        echo "api=${{ contains(steps.filter.outputs.changes, 'api') }}" >> $GITHUB_OUTPUT
        echo "shared=${{ contains(steps.filter.outputs.changes, 'shared') }}" >> $GITHUB_OUTPUT
        
        echo "📋 Change Detection Results:"
        echo "  frontend: ${{ contains(steps.filter.outputs.changes, 'frontend') }}"
        echo "  backend: ${{ contains(steps.filter.outputs.changes, 'backend') }}"
        echo "  api: ${{ contains(steps.filter.outputs.changes, 'api') }}"
        echo "  shared: ${{ contains(steps.filter.outputs.changes, 'shared') }}"